/** CRM mock data ported from `claude/CRM/data.jsx` — replace with API + Mongo. */

import { applyClientClickupFields, computeClv, computeLifetimeMonths } from "@/lib/crm/client-utils";
import { DOMAINS } from "@/lib/crm/domains-data";

export { DOMAINS };
export { computeClv, computeLifetimeMonths };

export const DEPARTMENTS = [
  { id: "seo", name: "SEO", color: "var(--dep-seo)", short: "SEO", capacity: 640 },
  { id: "ppc", name: "PPC", color: "var(--dep-ppc)", short: "PPC", capacity: 580 },
  { id: "social", name: "Paid Social", color: "var(--dep-social)", short: "PS", capacity: 380 },
  { id: "email", name: "E-mail", color: "var(--dep-email)", short: "EM", capacity: 260 },
  { id: "geo", name: "GEO", color: "var(--dep-geo)", short: "GEO", capacity: 160 },
  { id: "creative", name: "Creative", color: "var(--dep-creative)", short: "CR", capacity: 200 },
  { id: "content", name: "Content", color: "var(--dep-content)", short: "CN", capacity: 180 },
  { id: "martech", name: "MarTech", color: "var(--dep-martech)", short: "MT", capacity: 120 },
  { id: "web", name: "Web", color: "var(--dep-web)", short: "WB", capacity: 200 },
  { id: "cro", name: "CRO", color: "var(--dep-cro)", short: "CRO", capacity: 80 },
];

export const TEAM = [
  {
    id: "lm",
    name: "Louise Madsen",
    role: "Account Director",
    dept: "ppc",
    avatar: "LM",
    hue: 300,
    weeklyHours: 37,
    isMe: true,
  },
  { id: "mk", name: "Mikkel Kragh", role: "Head of PPC", dept: "ppc", avatar: "MK", hue: 272, weeklyHours: 37 },
  { id: "as", name: "Astrid Sørensen", role: "SEO Lead", dept: "seo", avatar: "AS", hue: 255, weeklyHours: 37 },
  { id: "ol", name: "Oliver Lange", role: "SEO Specialist", dept: "seo", avatar: "OL", hue: 250, weeklyHours: 37 },
  { id: "pe", name: "Pernille Eng", role: "SEO Specialist", dept: "seo", avatar: "PE", hue: 248, weeklyHours: 30 },
  { id: "ns", name: "Nikolaj Steen", role: "PPC Specialist", dept: "ppc", avatar: "NS", hue: 275, weeklyHours: 37 },
  { id: "jl", name: "Jonas Lindberg", role: "Paid Social", dept: "social", avatar: "JL", hue: 30, weeklyHours: 37 },
  { id: "sa", name: "Sara Albrektsen", role: "Paid Social", dept: "social", avatar: "SA", hue: 28, weeklyHours: 30 },
  { id: "es", name: "Emma Strøm", role: "Content Strategist", dept: "content", avatar: "ES", hue: 85, weeklyHours: 37 },
  { id: "rn", name: "Rasmus Nielsen", role: "Creative Director", dept: "creative", avatar: "RN", hue: 355, weeklyHours: 37 },
  { id: "iv", name: "Ivan Vestergaard", role: "Designer", dept: "creative", avatar: "IV", hue: 352, weeklyHours: 30 },
  { id: "kh", name: "Kristina Holm", role: "E-mail Specialist", dept: "email", avatar: "KH", hue: 180, weeklyHours: 37 },
  { id: "tp", name: "Tobias Peterson", role: "GEO Specialist", dept: "geo", avatar: "TP", hue: 135, weeklyHours: 37 },
];

function alloc(o) {
  const sum = Object.values(o).reduce((a, b) => a + b, 0);
  if (sum === 100) return o;
  const out = {};
  Object.entries(o).forEach(([k, v]) => {
    out[k] = Math.round((v / sum) * 100);
  });
  return out;
}

function npsHist(scores) {
  return scores.map((score, i) => ({
    score,
    sentAt: `2025-${String(5 + Math.floor(i / 2)).padStart(2, "0")}-${i % 2 === 0 ? "01" : "15"}`,
    respondedAt: `2025-${String(5 + Math.floor(i / 2)).padStart(2, "0")}-${i % 2 === 0 ? "03" : "17"}`,
  }));
}

const CLIENTS_RAW = [
  {
    id: "c-nordvig",
    name: "Nordvig & Partners",
    industry: "Law",
    logo: "NV",
    hue: 255,
    retainer: 72000,
    currency: "DKK",
    startedAt: "2024-03-01",
    renewalAt: "2026-06-30",
    status: "active",
    health: "ok",
    lastActivity: "2 timer siden",
    owner: "lm",
    allocation: alloc({ seo: 45, ppc: 18, content: 18, email: 8, clientMgmt: 7 }),
    servicesActive: ["seo", "ppc", "content", "email"],
    tags: ["Retainer", "Strategisk"],
    primaryContact: {
      name: "Katrine Lind",
      title: "Marketing Director",
      email: "katrine@nordvig.dk",
      phone: "+45 22 44 11 09",
    },
    secondaryContact: {
      name: "Henrik Jespersen",
      title: "CEO",
      email: "hj@nordvig.dk",
      phone: "+45 21 18 90 44",
    },
    hoursThisMonth: 46.5,
    hoursBudget: 62,
    monthlyProfitMargin: 0.31,
    utilisationHistory: [38, 42, 47, 51, 44, 48, 46, 52, 58, 49, 46, 46.5],
    npsHistory: npsHist([52, 55, 60, 58, 56, 62, 58]),
    npsInterval: "quarterly",
  },
  {
    id: "c-vaerft",
    name: "Værftet Hotels",
    industry: "Hospitality",
    logo: "VH",
    hue: 30,
    retainer: 95000,
    currency: "DKK",
    startedAt: "2023-08-15",
    renewalAt: "2026-05-15",
    status: "active",
    health: "bad",
    lastActivity: "5 min siden",
    owner: "mk",
    allocation: alloc({ ppc: 45, social: 30, creative: 15, seo: 10 }),
    servicesActive: ["ppc", "social", "creative", "seo"],
    tags: ["Over budget", "Eskaleret"],
    primaryContact: {
      name: "Signe Holm",
      title: "Head of Digital",
      email: "sh@vaerftet.com",
      phone: "+45 28 77 12 03",
    },
    secondaryContact: {
      name: "Magnus Brandt",
      title: "CMO",
      email: "magnus@vaerftet.com",
      phone: "+45 24 09 88 41",
    },
    hoursThisMonth: 112,
    hoursBudget: 84,
    monthlyProfitMargin: -0.08,
    utilisationHistory: [68, 72, 78, 81, 89, 95, 98, 102, 108, 110, 114, 112],
    npsHistory: npsHist([58, 54, 50, 48, 44, 38, 32]),
    npsInterval: "monthly",
  },
  {
    id: "c-folio",
    name: "Folio Furniture",
    industry: "E-commerce",
    logo: "FF",
    hue: 85,
    retainer: 54000,
    currency: "DKK",
    startedAt: "2025-01-10",
    renewalAt: "2026-07-10",
    status: "active",
    health: "ok",
    lastActivity: "1 dag siden",
    owner: "as",
    allocation: alloc({ seo: 35, ppc: 30, social: 20, content: 15 }),
    servicesActive: ["seo", "ppc", "social", "content"],
    tags: ["Vækst"],
    primaryContact: {
      name: "Pelle Ekman",
      title: "Head of Growth",
      email: "pelle@folio.shop",
      phone: "+46 70 992 44 18",
    },
    hoursThisMonth: 28,
    hoursBudget: 40,
    monthlyProfitMargin: 0.42,
    utilisationHistory: [22, 24, 27, 30, 29, 32, 31, 33, 30, 28, 26, 28],
    npsHistory: npsHist([65, 68, 70, 72, 71]),
    npsInterval: "quarterly",
  },
  {
    id: "c-brygg",
    name: "Bryggeriet Sort",
    industry: "FMCG",
    logo: "BS",
    hue: 355,
    retainer: 38000,
    currency: "DKK",
    startedAt: "2024-11-01",
    renewalAt: "2026-05-01",
    status: "active",
    health: "warn",
    lastActivity: "4 dage siden",
    owner: "jl",
    allocation: alloc({ social: 50, creative: 25, content: 15, email: 10 }),
    servicesActive: ["social", "creative", "content", "email"],
    tags: ["Kreativ", "Sæson"],
    primaryContact: {
      name: "Freja Østergaard",
      title: "Brand Manager",
      email: "freja@bryggsort.dk",
      phone: "+45 29 30 11 04",
    },
    hoursThisMonth: 34,
    hoursBudget: 32,
    monthlyProfitMargin: 0.08,
    utilisationHistory: [18, 22, 24, 28, 26, 29, 30, 31, 33, 32, 35, 34],
    npsHistory: npsHist([55, 52, 48, 49]),
    npsInterval: "quarterly",
  },
  {
    id: "c-torv",
    name: "Torvehallerne Group",
    industry: "Retail",
    logo: "TH",
    hue: 180,
    retainer: 120000,
    currency: "DKK",
    startedAt: "2022-04-01",
    renewalAt: "2026-09-01",
    status: "active",
    health: "ok",
    lastActivity: "20 min siden",
    owner: "kh",
    allocation: alloc({ email: 30, seo: 25, ppc: 25, social: 20 }),
    servicesActive: ["email", "seo", "ppc", "social", "content"],
    tags: ["Nøglekunde", "Enterprise"],
    primaryContact: {
      name: "Camilla Bach",
      title: "CDO",
      email: "cb@torvegroup.dk",
      phone: "+45 23 19 04 57",
    },
    secondaryContact: {
      name: "Oliver Frantzen",
      title: "Marketing Lead",
      email: "of@torvegroup.dk",
      phone: "+45 28 77 03 19",
    },
    hoursThisMonth: 78,
    hoursBudget: 110,
    monthlyProfitMargin: 0.38,
    utilisationHistory: [65, 70, 72, 74, 76, 78, 80, 82, 84, 81, 79, 78],
    npsHistory: npsHist([76, 78, 80, 82, 81, 82]),
    npsInterval: "monthly",
  },
  {
    id: "c-axel",
    name: "Axelborg Dental",
    industry: "Healthcare",
    logo: "AD",
    hue: 135,
    retainer: 22000,
    currency: "DKK",
    startedAt: "2025-09-15",
    renewalAt: "2026-04-15",
    status: "paused",
    health: "warn",
    lastActivity: "11 dage siden",
    owner: "tp",
    allocation: alloc({ geo: 60, seo: 25, ppc: 15 }),
    servicesActive: ["geo", "seo", "ppc"],
    tags: ["Lokal", "Pauseret"],
    primaryContact: {
      name: "Dr. Niels Bertram",
      title: "Partner",
      email: "nb@axelborg.dk",
      phone: "+45 25 18 00 11",
    },
    hoursThisMonth: 14,
    hoursBudget: 18,
    monthlyProfitMargin: 0.18,
    utilisationHistory: [10, 11, 13, 14, 12, 15, 14, 16, 13, 15, 14, 14],
    npsHistory: npsHist([48, 44]),
    npsInterval: "biannual",
  },
  {
    id: "c-kyst",
    name: "Kystlinjen Rejser",
    industry: "Travel",
    logo: "KR",
    hue: 220,
    retainer: 64000,
    currency: "DKK",
    startedAt: "2024-06-01",
    renewalAt: "2026-06-01",
    status: "active",
    health: "ok",
    lastActivity: "3 timer siden",
    owner: "jl",
    allocation: alloc({ social: 35, ppc: 30, creative: 20, email: 15 }),
    servicesActive: ["social", "ppc", "creative", "email"],
    tags: ["Sæson", "Rejse"],
    primaryContact: {
      name: "Mette Juul",
      title: "CMO",
      email: "mj@kystlinjen.dk",
      phone: "+45 22 98 14 67",
    },
    hoursThisMonth: 42,
    hoursBudget: 56,
    monthlyProfitMargin: 0.27,
    utilisationHistory: [35, 38, 40, 44, 46, 48, 50, 52, 48, 45, 43, 42],
    npsHistory: npsHist([60, 62, 64, 66, 64]),
    npsInterval: "quarterly",
  },
  {
    id: "c-helio",
    name: "Helio Solar",
    industry: "Energy",
    logo: "HS",
    hue: 60,
    retainer: 88000,
    currency: "DKK",
    startedAt: "2024-10-01",
    renewalAt: "2026-10-01",
    status: "active",
    health: "bad",
    lastActivity: "7 dage siden",
    owner: "mk",
    allocation: alloc({ ppc: 40, geo: 25, seo: 20, content: 15 }),
    servicesActive: ["ppc", "geo", "seo", "content"],
    tags: ["Over budget"],
    primaryContact: {
      name: "Thor Lindhardt",
      title: "Head of Marketing",
      email: "tl@helio.dk",
      phone: "+45 20 11 33 88",
    },
    hoursThisMonth: 98,
    hoursBudget: 72,
    monthlyProfitMargin: -0.04,
    utilisationHistory: [55, 60, 65, 70, 78, 84, 90, 94, 98, 100, 97, 98],
    npsHistory: npsHist([48, 45, 42, 40, 38]),
    npsInterval: "monthly",
  },
  {
    id: "c-norden",
    name: "Norden Finans",
    industry: "Finance",
    logo: "NF",
    hue: 200,
    retainer: 140000,
    currency: "DKK",
    startedAt: "2021-09-01",
    renewalAt: "2026-08-31",
    status: "active",
    health: "ok",
    lastActivity: "45 min siden",
    owner: "lm",
    allocation: alloc({ seo: 30, ppc: 25, content: 25, email: 10, social: 10 }),
    servicesActive: ["seo", "ppc", "content", "email", "social"],
    tags: ["Nøglekunde", "Langsigtet"],
    primaryContact: {
      name: "Victoria Aas",
      title: "VP Growth",
      email: "va@nordenfinans.com",
      phone: "+45 29 07 21 14",
    },
    secondaryContact: {
      name: "Christian Wiese",
      title: "Marketing Manager",
      email: "cw@nordenfinans.com",
      phone: "+45 22 48 19 03",
    },
    hoursThisMonth: 92,
    hoursBudget: 130,
    monthlyProfitMargin: 0.44,
    utilisationHistory: [85, 88, 90, 92, 95, 98, 94, 90, 88, 90, 91, 92],
    npsHistory: npsHist([70, 72, 74, 76, 76]),
    npsInterval: "quarterly",
  },
  {
    id: "c-blaa",
    name: "Blaa Planet",
    industry: "NGO",
    logo: "BP",
    hue: 195,
    retainer: 28000,
    currency: "DKK",
    startedAt: "2024-05-01",
    renewalAt: "2026-05-01",
    status: "inactive",
    health: "warn",
    lastActivity: "18 dage siden",
    owner: "es",
    allocation: alloc({ content: 45, seo: 25, social: 20, email: 10 }),
    servicesActive: ["content", "seo", "social", "email"],
    tags: ["Inaktiv"],
    primaryContact: {
      name: "Sara Kjær",
      title: "Communications",
      email: "sk@blaaplanet.org",
      phone: "+45 26 55 09 12",
    },
    hoursThisMonth: 6,
    hoursBudget: 24,
    monthlyProfitMargin: 0.12,
    utilisationHistory: [20, 22, 19, 18, 16, 14, 12, 10, 8, 6, 6, 6],
    npsHistory: npsHist([55, 51]),
    npsInterval: "quarterly",
  },
  {
    id: "c-edge",
    name: "Edge Performance",
    industry: "Fitness",
    logo: "EP",
    hue: 15,
    retainer: 45000,
    currency: "DKK",
    startedAt: "2025-03-01",
    renewalAt: "2026-09-01",
    status: "active",
    health: "ok",
    lastActivity: "6 timer siden",
    owner: "rn",
    allocation: alloc({ social: 40, creative: 30, ppc: 20, content: 10 }),
    servicesActive: ["social", "creative", "ppc", "content"],
    tags: ["Brand"],
    primaryContact: {
      name: "Frederik Lund",
      title: "Founder",
      email: "fl@edge.fit",
      phone: "+45 23 31 04 95",
    },
    hoursThisMonth: 32,
    hoursBudget: 42,
    monthlyProfitMargin: 0.29,
    utilisationHistory: [25, 28, 30, 31, 32, 34, 36, 33, 30, 31, 32, 32],
    npsHistory: npsHist([62, 66, 68, 69]),
    npsInterval: "quarterly",
  },
  {
    id: "c-matr",
    name: "Matr. Arkitekter",
    industry: "Architecture",
    logo: "MA",
    hue: 40,
    retainer: 34000,
    currency: "DKK",
    startedAt: "2024-09-01",
    renewalAt: "2026-09-01",
    status: "active",
    health: "ok",
    lastActivity: "9 timer siden",
    owner: "es",
    allocation: alloc({ content: 35, seo: 30, social: 20, creative: 15 }),
    servicesActive: ["content", "seo", "social", "creative"],
    tags: ["Premium"],
    primaryContact: {
      name: "Ida Berg",
      title: "Partner",
      email: "ib@matr.dk",
      phone: "+45 22 04 77 18",
    },
    hoursThisMonth: 24,
    hoursBudget: 30,
    monthlyProfitMargin: 0.33,
    utilisationHistory: [20, 22, 24, 25, 23, 26, 27, 25, 24, 23, 24, 24],
    npsHistory: npsHist([70, 72, 73]),
    npsInterval: "biannual",
  },
  {
    id: "c-lava",
    name: "Lava Kaffe",
    industry: "FMCG",
    logo: "LK",
    hue: 20,
    retainer: 42000,
    currency: "DKK",
    startedAt: "2025-02-15",
    renewalAt: "2026-08-15",
    status: "active",
    health: "warn",
    lastActivity: "2 dage siden",
    owner: "jl",
    allocation: alloc({ social: 40, creative: 25, ppc: 20, email: 15 }),
    servicesActive: ["social", "creative", "ppc", "email"],
    tags: ["D2C"],
    primaryContact: {
      name: "Nanna Engdahl",
      title: "Head of Growth",
      email: "ne@lava.coffee",
      phone: "+45 25 88 19 03",
    },
    hoursThisMonth: 38,
    hoursBudget: 34,
    monthlyProfitMargin: 0.04,
    utilisationHistory: [22, 26, 28, 30, 32, 35, 36, 38, 37, 36, 37, 38],
    npsHistory: npsHist([54, 50, 48, 47]),
    npsInterval: "monthly",
  },
  {
    id: "c-polar",
    name: "Polar Textile",
    industry: "Fashion",
    logo: "PT",
    hue: 265,
    retainer: 58000,
    currency: "DKK",
    startedAt: "2024-04-01",
    renewalAt: "2026-04-30",
    status: "active",
    health: "ok",
    lastActivity: "1 time siden",
    owner: "as",
    allocation: alloc({ seo: 35, ppc: 30, social: 20, content: 15 }),
    servicesActive: ["seo", "ppc", "social", "content"],
    tags: ["E-com"],
    primaryContact: {
      name: "Rikke Thorsen",
      title: "Ecom Manager",
      email: "rt@polar.dk",
      phone: "+45 22 73 04 18",
    },
    hoursThisMonth: 44,
    hoursBudget: 54,
    monthlyProfitMargin: 0.26,
    utilisationHistory: [36, 38, 40, 42, 44, 46, 48, 46, 44, 42, 44, 44],
    npsHistory: npsHist([62, 64, 66, 66]),
    npsInterval: "quarterly",
  },
  {
    id: "c-sund",
    name: "Sundby Klinik",
    industry: "Healthcare",
    logo: "SK",
    hue: 150,
    retainer: 18000,
    currency: "DKK",
    startedAt: "2025-06-01",
    renewalAt: "2026-06-01",
    status: "active",
    health: "ok",
    lastActivity: "2 dage siden",
    owner: "tp",
    allocation: alloc({ geo: 55, seo: 30, ppc: 15 }),
    servicesActive: ["geo", "seo", "ppc"],
    tags: ["Lokal"],
    primaryContact: {
      name: "Lars Mortensen",
      title: "Ejer",
      email: "lm@sundbyklinik.dk",
      phone: "+45 22 09 18 77",
    },
    hoursThisMonth: 10,
    hoursBudget: 14,
    monthlyProfitMargin: 0.22,
    utilisationHistory: [8, 9, 10, 11, 10, 12, 11, 10, 11, 10, 10, 10],
    npsHistory: npsHist([58, 61]),
    npsInterval: "biannual",
  },
  {
    id: "c-hof",
    name: "Hof Meubelen",
    industry: "Furniture",
    logo: "HM",
    hue: 45,
    retainer: 68000,
    currency: "EUR",
    startedAt: "2024-02-01",
    renewalAt: "2026-08-01",
    status: "active",
    health: "ok",
    lastActivity: "12 timer siden",
    owner: "kh",
    allocation: alloc({ seo: 30, email: 25, ppc: 25, content: 20 }),
    servicesActive: ["seo", "email", "ppc", "content"],
    tags: ["EU", "Multi-lang"],
    primaryContact: {
      name: "Eva van Dijk",
      title: "Online Manager",
      email: "eva@hofmeubelen.nl",
      phone: "+31 20 412 88 19",
    },
    hoursThisMonth: 52,
    hoursBudget: 66,
    monthlyProfitMargin: 0.31,
    utilisationHistory: [42, 46, 50, 54, 52, 55, 54, 52, 50, 51, 53, 52],
    npsHistory: npsHist([66, 68, 70, 70]),
    npsInterval: "quarterly",
  },
  {
    id: "c-kerne",
    name: "Kerne Bageri",
    industry: "Food",
    logo: "KB",
    hue: 75,
    retainer: 24000,
    currency: "DKK",
    startedAt: "2025-08-01",
    renewalAt: "2026-08-01",
    status: "active",
    health: "ok",
    lastActivity: "4 timer siden",
    owner: "rn",
    allocation: alloc({ social: 50, creative: 30, content: 20 }),
    servicesActive: ["social", "creative", "content"],
    tags: ["Lokal"],
    primaryContact: {
      name: "Anders Krogh",
      title: "Ejer",
      email: "ak@kernebageri.dk",
      phone: "+45 28 11 44 09",
    },
    hoursThisMonth: 18,
    hoursBudget: 20,
    monthlyProfitMargin: 0.21,
    utilisationHistory: [12, 14, 15, 16, 17, 18, 19, 18, 17, 18, 18, 18],
    npsHistory: npsHist([64, 68]),
    npsInterval: "biannual",
  },
  {
    id: "c-vind",
    name: "Vind Logistik",
    industry: "Logistics",
    logo: "VL",
    hue: 210,
    retainer: 82000,
    currency: "DKK",
    startedAt: "2023-11-01",
    renewalAt: "2026-05-01",
    status: "active",
    health: "ok",
    lastActivity: "8 timer siden",
    owner: "mk",
    allocation: alloc({ ppc: 35, seo: 30, content: 20, email: 15 }),
    servicesActive: ["ppc", "seo", "content", "email"],
    tags: ["B2B"],
    primaryContact: {
      name: "Jakob Strand",
      title: "Growth Lead",
      email: "js@vindlogistik.dk",
      phone: "+45 22 55 19 08",
    },
    hoursThisMonth: 62,
    hoursBudget: 78,
    monthlyProfitMargin: 0.34,
    utilisationHistory: [52, 56, 58, 60, 62, 65, 64, 62, 60, 61, 62, 62],
    npsHistory: npsHist([64, 66, 67, 68, 67]),
    npsInterval: "quarterly",
  },
];

/** @typedef {ReturnType<typeof applyClientClickupFields>} CrmClient */

export const CLIENTS = /** @type {CrmClient[]} */ (
  CLIENTS_RAW.map((c) => applyClientClickupFields(c))
);

/** Demo kontrakter — én primær aftale pr. kunde (Mongo Contract-model senere). */
export const CONTRACTS = CLIENTS.map((c, i) => {
  const kinds = /** @type {const} */ (["Retainer", "Rammeaftale", "Projekt"]);
  return {
    id: `ctr-${c.id}`,
    clientId: c.id,
    clientName: c.name,
    clientLogo: c.logo,
    clientHue: c.hue,
    kind: kinds[i % kinds.length],
    monthlyValue: c.retainer,
    currency: c.currency,
    startedAt: c.startedAt,
    renewalAt: c.renewalAt,
    accountStatus: c.status,
    health: c.health,
    ownerId: c.owner,
    noticeDays: [30, 45, 60, 90][i % 4],
    documentUrl: `https://drive.google.com/file/d/demo-${c.id}/view`,
    signedBy: c.primaryContact?.name ?? null,
  };
});

/** @type {Record<string, { id: string; at: string; kind: string; summary: string }[]>} */
export const CONTRACT_REVISION_LOG = {};
CONTRACTS.forEach((ctr) => {
  const base = [
    {
      id: `${ctr.id}-ev-1`,
      at: "2026-03-14",
      kind: "Økonomi",
      summary: `Beløb og valuta stemt mod regnskab efter Q1-gennemgang (${ctr.currency}).`,
    },
    {
      id: `${ctr.id}-ev-2`,
      at: ctr.startedAt,
      kind: "Aktivering",
      summary: `${ctr.kind} oprettet med ${ctr.noticeDays} kalenderdages opsigelse.`,
    },
  ];
  CONTRACT_REVISION_LOG[ctr.id] =
    ctr.kind === "Projekt"
      ? [
          ...base,
          {
            id: `${ctr.id}-ev-3`,
            at: "2025-10-20",
            kind: "Scope",
            summary: "Workshop-gennemgang og milepæle for fast-track leverance (mock).",
          },
        ]
      : base;
});

/** Demo-opgaver (Mongo Task-/WorkItem-model senere). */
export const TASKS = [
  {
    id: "t-nv-q2-report",
    title: "Kvartalsrapport SEO — Q2-udkast",
    hint: "CWV + indeksering.",
    clientId: "c-nordvig",
    clientName: "Nordvig & Partners",
    clientLogo: "NV",
    clientHue: 255,
    assigneeId: "as",
    dept: "seo",
    status: "doing",
    priority: "high",
    dueDate: "2026-05-14",
  },
  {
    id: "t-vf-hours",
    title: "Budget-gennemgang tidsforbrug",
    hint: "Eskalering til kunde.",
    clientId: "c-vaerft",
    clientName: "Værftet Hotels",
    clientLogo: "VH",
    clientHue: 30,
    assigneeId: "lm",
    dept: "ppc",
    status: "review",
    priority: "high",
    dueDate: "2026-05-06",
  },
  {
    id: "t-vf-meta",
    title: "Campaign revision — sommerkampanje",
    clientId: "c-vaerft",
    clientName: "Værftet Hotels",
    clientLogo: "VH",
    clientHue: 30,
    assigneeId: "mk",
    dept: "ppc",
    status: "doing",
    priority: "medium",
    dueDate: "2026-05-22",
  },
  {
    id: "t-ff-feed",
    title: "Merchant Center feed-oprydning",
    clientId: "c-folio",
    clientName: "Folio Furniture",
    clientLogo: "FF",
    clientHue: 85,
    assigneeId: "ns",
    dept: "ppc",
    status: "todo",
    priority: "medium",
    dueDate: "2026-05-03",
  },
  {
    id: "t-brygg-reel",
    title: "Kreativpakke — IG Reels (3 stk.)",
    clientId: "c-brygg",
    clientName: "Bryggeriet Sort",
    clientLogo: "BS",
    clientHue: 355,
    assigneeId: "jl",
    dept: "social",
    status: "doing",
    priority: "low",
    dueDate: "2026-05-28",
  },
  {
    id: "t-torv-drip",
    title: "E-mail flow onboarding",
    clientId: "c-torv",
    clientName: "Torvehallerne Group",
    clientLogo: "TH",
    clientHue: 180,
    assigneeId: "kh",
    dept: "email",
    status: "todo",
    priority: "high",
    dueDate: "2026-04-29",
  },
  {
    id: "t-axel-blog",
    title: "Blogindlæg — Invisalign FAQ",
    clientId: "c-axel",
    clientName: "Axelborg Dental",
    clientLogo: "AD",
    clientHue: 135,
    assigneeId: "tp",
    dept: "geo",
    status: "blocked",
    priority: "low",
    dueDate: "2026-05-11",
  },
  {
    id: "t-kyst-landing",
    title: "LP sommersalg — DK/SE",
    clientId: "c-kyst",
    clientName: "Kystlinjen Rejser",
    clientLogo: "KR",
    clientHue: 220,
    assigneeId: "sa",
    dept: "social",
    status: "doing",
    priority: "high",
    dueDate: "2026-05-09",
  },
  {
    id: "t-helio-bid-cap",
    title: "PMax — revisér budloft & signals",
    clientId: "c-helio",
    clientName: "Helio Solar",
    clientLogo: "HS",
    clientHue: 60,
    assigneeId: "mk",
    dept: "ppc",
    status: "review",
    priority: "high",
    dueDate: "2026-05-07",
  },
  {
    id: "t-norden-copy",
    title: "Finans disclaimers på annoncer",
    clientId: "c-norden",
    clientName: "Norden Finans",
    clientLogo: "NF",
    clientHue: 200,
    assigneeId: "lm",
    dept: "ppc",
    status: "done",
    priority: "high",
    dueDate: "2026-05-01",
  },
  {
    id: "t-blaa-donation",
    title: "Donation-kampagne meta opsætning",
    clientId: "c-blaa",
    clientName: "Blaa Planet",
    clientLogo: "BP",
    clientHue: 195,
    assigneeId: "jl",
    dept: "social",
    status: "todo",
    priority: "medium",
    dueDate: "2026-05-20",
  },
  {
    id: "t-edge-landing",
    title: "A/B-test hero på forsiden",
    clientId: "c-edge",
    clientName: "Edge Performance",
    clientLogo: "EP",
    clientHue: 15,
    assigneeId: "iv",
    dept: "creative",
    status: "doing",
    priority: "medium",
    dueDate: "2026-04-30",
  },
  {
    id: "t-matr-casestudy",
    title: "Kundehistorie — kontorhaus",
    clientId: "c-matr",
    clientName: "Matr. Arkitekter",
    clientLogo: "MA",
    clientHue: 40,
    assigneeId: "es",
    dept: "content",
    status: "todo",
    priority: "low",
    dueDate: "2026-06-04",
  },
  {
    id: "t-lava-ugc",
    title: "UGC brief til mikroindsamlere",
    clientId: "c-lava",
    clientName: "Lava Kaffe",
    clientLogo: "LK",
    clientHue: 20,
    assigneeId: "rn",
    dept: "creative",
    status: "review",
    priority: "low",
    dueDate: "2026-05-18",
  },
  {
    id: "t-polar-shopping",
    title: "CSS feed — Supplemental source",
    clientId: "c-polar",
    clientName: "Polar Textile",
    clientLogo: "PT",
    clientHue: 265,
    assigneeId: "ns",
    dept: "ppc",
    status: "doing",
    priority: "medium",
    dueDate: "2026-05-02",
  },
  {
    id: "t-sund-ga4",
    title: "GA4 — mål på telefonbooking",
    clientId: "c-sund",
    clientName: "Sundby Klinik",
    clientLogo: "SK",
    clientHue: 150,
    assigneeId: "lm",
    dept: "seo",
    status: "todo",
    priority: "high",
    dueDate: "2026-05-05",
  },
  {
    id: "t-hof-catalog",
    title: "Remarketingliste — sofasæt kampanje",
    clientId: "c-hof",
    clientName: "Hof Meubelen",
    clientLogo: "HM",
    clientHue: 45,
    assigneeId: "mk",
    dept: "ppc",
    status: "done",
    priority: "medium",
    dueDate: "2026-04-20",
  },
  {
    id: "t-kerne-calendar",
    title: "Indholdskalender Q2 opslag",
    clientId: "c-kerne",
    clientName: "Kerne Bageri",
    clientLogo: "KB",
    clientHue: 75,
    assigneeId: "es",
    dept: "content",
    status: "doing",
    priority: "low",
    dueDate: "2026-05-25",
  },
  {
    id: "t-vind-whitepaper",
    title: "Lead magnet PDF + form",
    clientId: "c-vind",
    clientName: "Vind Logistik",
    clientLogo: "VL",
    clientHue: 210,
    assigneeId: "ol",
    dept: "seo",
    status: "todo",
    priority: "medium",
    dueDate: "2026-04-26",
  },
  {
    id: "t-nv-call",
    title: "Månedlig status-call (slides)",
    clientId: "c-nordvig",
    clientName: "Nordvig & Partners",
    clientLogo: "NV",
    clientHue: 255,
    assigneeId: "lm",
    dept: "ppc",
    status: "review",
    priority: "medium",
    dueDate: "2026-05-12",
  },
  {
    id: "t-pe-technical",
    title: "Schema.org Organisation opdateres",
    clientId: "c-nordvig",
    clientName: "Nordvig & Partners",
    clientLogo: "NV",
    clientHue: 255,
    assigneeId: "pe",
    dept: "seo",
    status: "done",
    priority: "low",
    dueDate: "2026-04-18",
  },
  {
    id: "t-vaerft-qa",
    title: "Kvalitetssikring kampanje-URLs",
    clientId: "c-vaerft",
    clientName: "Værftet Hotels",
    clientLogo: "VH",
    clientHue: 30,
    assigneeId: "lm",
    dept: "ppc",
    status: "todo",
    priority: "high",
    dueDate: "2026-05-01",
  },
];

/** @type {Record<string, { id: string; at: string; actorId: string; kind: string; body: string }[]>} */
export const TASK_ACTIVITY_LOG = {};
TASKS.forEach((t) => {
  TASK_ACTIVITY_LOG[t.id] = [
    {
      id: `${t.id}-act-1`,
      at: "2026-04-22 11:30",
      actorId: t.assigneeId,
      kind: "Notat",
      body: `${t.priority === "high" ? "[Høj prio] " : ""}Status fra seneste stand-up — afhængigheder er synlige i boardet.`,
    },
    {
      id: `${t.id}-act-2`,
      at: "2026-04-08 09:00",
      actorId: t.assigneeId,
      kind: "Oprettelse",
      body: "Opgave provisioneret automatisk ud fra aftale-scope (CRM → Task-motor, mock).",
    },
    ...(t.status === "blocked"
      ? [
          {
            id: `${t.id}-act-b`,
            at: "2026-05-03 08:42",
            actorId: "lm",
            kind: "Blokering",
            body: "Afvent input fra kunden — dokumentation sendt på e-mail.",
          },
        ]
      : []),
  ];
});

/** Standard work-item skabeloner til provisionering (Mongo TaskTemplate senere). */
export const TASK_TEMPLATES = [
  {
    id: "tt-seo-cwv",
    name: "Kvartals-audit — Core Web Vitals",
    hint: "Teknisk rapport, anbefalinger og opfølgning i board.",
    dept: "seo",
    defaultPriority: "high",
    defaultDueOffsetDays: 14,
    estHours: 12,
    checklistCount: 8,
    scope: "retainer",
    active: true,
    updatedAt: "2026-04-28",
    usedCount: 34,
  },
  {
    id: "tt-ppc-pmax",
    name: "PMax — struktur, signals & exclusions",
    hint: "Campagnestruktur, audience signals og negativer efter playbook.",
    dept: "ppc",
    defaultPriority: "high",
    defaultDueOffsetDays: 10,
    estHours: 8,
    checklistCount: 6,
    scope: "retainer",
    active: true,
    updatedAt: "2026-05-02",
    usedCount: 52,
  },
  {
    id: "tt-ppc-feed-audit",
    name: "Merchant Center — feed sanity check",
    hint: "Titles, GTIN, landing page match og policy flags.",
    dept: "ppc",
    defaultPriority: "high",
    defaultDueOffsetDays: 5,
    estHours: 4,
    checklistCount: 6,
    scope: "retainer",
    active: true,
    updatedAt: "2026-04-09",
    usedCount: 41,
  },
  {
    id: "tt-social-ugc",
    name: "UGC / creator brief pakke",
    hint: "Brief, references og safe-zone til paid + organisk.",
    dept: "social",
    defaultPriority: "medium",
    defaultDueOffsetDays: 7,
    estHours: 4,
    checklistCount: 5,
    scope: "any",
    active: true,
    updatedAt: "2026-03-30",
    usedCount: 19,
  },
  {
    id: "tt-email-onboard",
    name: "Onboarding drip (3 mail)",
    hint: "Velkomst → værdi → CTA; link tracking sat op.",
    dept: "email",
    defaultPriority: "medium",
    defaultDueOffsetDays: 21,
    estHours: 6,
    checklistCount: 10,
    scope: "retainer",
    active: true,
    updatedAt: "2026-04-14",
    usedCount: 27,
  },
  {
    id: "tt-email-legacy",
    name: "DOI flow v1 (forældet)",
    hint: "Erstattet af dobbelt-opt-in v2 — beholdes som reference.",
    dept: "email",
    defaultPriority: "low",
    defaultDueOffsetDays: 14,
    estHours: 3,
    checklistCount: 4,
    scope: "retainer",
    active: false,
    updatedAt: "2025-11-02",
    usedCount: 3,
  },
  {
    id: "tt-geo-gbp",
    name: "Google Business Profile — optimeringspakke",
    hint: "Kategorier, posts, Q&A og review-respons skabelon.",
    dept: "geo",
    defaultPriority: "low",
    defaultDueOffsetDays: 30,
    estHours: 5,
    checklistCount: 4,
    scope: "project",
    active: true,
    updatedAt: "2026-01-20",
    usedCount: 11,
  },
  {
    id: "tt-creative-reels",
    name: "Reel-pakke (3 stk.)",
    hint: "Storyboard, caption bank og export-specs pr. platform.",
    dept: "creative",
    defaultPriority: "medium",
    defaultDueOffsetDays: 14,
    estHours: 16,
    checklistCount: 7,
    scope: "any",
    active: true,
    updatedAt: "2026-05-05",
    usedCount: 22,
  },
  {
    id: "tt-content-editorial",
    name: "Redaktionel kalender (kvartal)",
    hint: "Pille + SEO-vinkler + approval flow.",
    dept: "content",
    defaultPriority: "low",
    defaultDueOffsetDays: 5,
    estHours: 3,
    checklistCount: 12,
    scope: "retainer",
    active: true,
    updatedAt: "2026-04-01",
    usedCount: 16,
  },
  {
    id: "tt-seo-schema",
    name: "Schema.org — organisation + service",
    hint: "Markup, validering og deploy-checkliste.",
    dept: "seo",
    defaultPriority: "medium",
    defaultDueOffsetDays: 7,
    estHours: 5,
    checklistCount: 5,
    scope: "project",
    active: true,
    updatedAt: "2026-03-18",
    usedCount: 18,
  },
];

/** @type {Record<string, { month: string, retainer: number, currency: string }[]>} */
export const RETAINER_HISTORY = {};
CLIENTS.forEach((c) => {
  const months = ["2025-11", "2025-12", "2026-01", "2026-02", "2026-03", "2026-04"];
  RETAINER_HISTORY[c.id] = months.map((m, i) => {
    let amt = c.retainer;
    if (c.id === "c-vaerft" && i < 3) amt = 75000;
    if (c.id === "c-norden" && i < 2) amt = 120000;
    if (c.id === "c-folio" && i < 2) amt = 42000;
    return { month: m, retainer: amt, currency: c.currency };
  });
});

export const NOTES_BY_CLIENT = {
  "c-nordvig": [
    {
      id: "n1",
      who: "as",
      at: "2026-04-18 14:22",
      type: "note",
      body: "Drøftet Q2-roadmap med Katrine. De vil have mere fokus på technical SEO og Core Web Vitals før juni.",
    },
    {
      id: "n2",
      who: "lm",
      at: "2026-04-16 09:10",
      type: "call",
      body: "Status-call (30 min). Alt grønt. Henrik vil diskutere retainer-udvidelse i maj.",
    },
    {
      id: "n3",
      who: "as",
      at: "2026-04-14 11:45",
      type: "note",
      body: "Færdiggjort Q1-rapport og delt med kunden.",
    },
    {
      id: "n4",
      who: "mk",
      at: "2026-04-10 16:00",
      type: "meeting",
      body: "Strategimøde aflyst — flyttes til uge 17.",
    },
  ],
  "c-vaerft": [
    {
      id: "n1",
      who: "mk",
      at: "2026-04-20 08:02",
      type: "alert",
      body: "🚩 Tidsforbrug overstiger budget med 33%. Eskaleret til Louise.",
    },
    {
      id: "n2",
      who: "lm",
      at: "2026-04-19 14:18",
      type: "note",
      body: "Signe erkender at scope er vokset. Foreslår vi workshopper budget om i uge 17.",
    },
    {
      id: "n3",
      who: "mk",
      at: "2026-04-18 10:30",
      type: "call",
      body: "Krisemøde med Magnus. De er bekymrede over ROAS på Meta.",
    },
  ],
};

CLIENTS.forEach((c) => {
  if (!NOTES_BY_CLIENT[c.id]) {
    NOTES_BY_CLIENT[c.id] = [
      {
        id: `${c.id}-gen-1`,
        who: c.owner,
        at: "2026-04-28 11:20",
        type: "note",
        body: `Statusnotat: ${c.industry}-konto (${c.tags?.join(", ") || "uden tags"}). Seneste aktivitet ${c.lastActivity}.`,
      },
      {
        id: `${c.id}-gen-2`,
        who: c.owner,
        at: "2026-04-05 09:05",
        type: "call",
        body:
          c.health === "ok"
            ? "Kort checkpoint om leverancer — alt ifølge plan i mock-perioden."
            : "Udvidet call om budget, sundhedscore og kommende milestones — se Pulse-alerts på tværs af konti.",
      },
    ];
  }
});

export const AGENCY_METRICS = {
  retainerMRR: 1092000,
  retainerMRRPrev: 1036000,
  utilisation: 0.74,
  utilisationPrev: 0.71,
  overheadPct: 0.21,
  overheadPctPrev: 0.19,
  billableHoursMonth: 1847,
  billableHoursPrev: 1712,
  avgMargin: 0.28,
  avgMarginPrev: 0.26,
  activeClients: CLIENTS.filter((c) => c.status === "active").length,
  healthyClients: CLIENTS.filter((c) => c.health === "ok" && c.status === "active").length,
  warnClients: CLIENTS.filter((c) => c.health === "warn" && c.status === "active").length,
  badClients: CLIENTS.filter((c) => c.health === "bad" && c.status === "active").length,
};

export const DEPT_PERFORMANCE = [
  { dept: "seo", revenue: 312000, hours: 486, budget: 520, util: 0.93 },
  { dept: "ppc", revenue: 298000, hours: 522, budget: 480, util: 1.09 },
  { dept: "social", revenue: 186000, hours: 318, budget: 340, util: 0.94 },
  { dept: "email", revenue: 124000, hours: 188, budget: 220, util: 0.85 },
  { dept: "geo", revenue: 72000, hours: 104, budget: 120, util: 0.87 },
  { dept: "creative", revenue: 64000, hours: 132, budget: 140, util: 0.94 },
  { dept: "content", revenue: 36000, hours: 97, budget: 110, util: 0.88 },
];

/** Deterministic series (no `Math.random`) for stable SSR */
export const UTIL_TREND = Array.from({ length: 30 }, (_, i) => ({
  day: i + 1,
  billable: 58 + Math.sin(i / 4) * 8 + ((i * 7) % 6),
  overhead: 18 + Math.cos(i / 3) * 4 + ((i * 5) % 3),
}));

export const SMART_ALERTS = [
  {
    id: "a1",
    severity: "bad",
    client: "c-vaerft",
    type: "overBudget",
    title: "Værftet Hotels — 33% over budget",
    body: "112 / 84 t i april. Margin -8%. Eskaleret.",
    age: "nu",
  },
  {
    id: "a2",
    severity: "bad",
    client: "c-helio",
    type: "overBudget",
    title: "Helio Solar — 36% over budget",
    body: "98 / 72 t i april. Margin -4%.",
    age: "2 t",
  },
  {
    id: "a3",
    severity: "warn",
    client: "c-vaerft",
    type: "npsDrop",
    title: "Værftet Hotels — NPS falder",
    body: "NPS faldet fra 58 → 32 på 60 dage.",
    age: "3 t",
  },
  {
    id: "a4",
    severity: "warn",
    client: "c-blaa",
    type: "inactive",
    title: "Blaa Planet — markeret inaktiv",
    body: "Ingen loggede timer siden 2. april.",
    age: "1 d",
  },
  {
    id: "a5",
    severity: "warn",
    client: null,
    type: "overhead",
    title: "Overhead-tid: 21% (mål: 15%)",
    body: "Non-billable tid er steget over tærsklen denne uge.",
    age: "1 d",
  },
  {
    id: "a6",
    severity: "warn",
    client: "c-lava",
    type: "overBudget",
    title: "Lava Kaffe — 12% over budget",
    body: "38 / 34 t i april. Margin +4%.",
    age: "2 d",
  },
];

/** Mål pr. arbejdsdag (minutter) — 7,5 t, matcher Agency OS playbook (mock). */
export const TIME_DAILY_TARGET_MINUTES = 450;

/**
 * Ugereolen omkring `TASK_DEMO_REF_DATE` i task-utils (`2026-05-08`).
 * `minutes: null` = aktiv dag; UI erstatter med summen af {@link TIME_ENTRIES_TODAY}.
 */
export const TIME_WEEK_OVERVIEW = [
  { iso: "2026-05-04", label: "Man", minutes: 392 },
  { iso: "2026-05-05", label: "Tir", minutes: 451 },
  { iso: "2026-05-06", label: "Ons", minutes: 403 },
  { iso: "2026-05-07", label: "Tor", minutes: 465 },
  { iso: "2026-05-08", label: "Fre", minutes: null },
  { iso: "2026-05-09", label: "Lør", minutes: 0 },
  { iso: "2026-05-10", label: "Søn", minutes: 0 },
];

export const TIME_ENTRIES_TODAY = [
  {
    id: "e1",
    at: "09:15",
    dur: 45,
    client: "c-nordvig",
    dept: "seo",
    task: "t-nv-q2-report",
    desc: "Core Web Vitals audit",
  },
  {
    id: "e2",
    at: "10:30",
    dur: 30,
    client: "c-torv",
    dept: "email",
    task: null,
    desc: "Nyhedsbrev review",
  },
  {
    id: "e3",
    at: "11:15",
    dur: 90,
    client: "c-nordvig",
    dept: "seo",
    task: "t-nv-q2-report",
    desc: "Indexation report + crawl fixes",
  },
  {
    id: "e4",
    at: "13:30",
    dur: 60,
    client: "c-folio",
    dept: "ppc",
    task: null,
    desc: "Kampagne-optimering",
  },
  {
    id: "e5",
    at: "14:45",
    dur: 25,
    client: null,
    dept: null,
    task: null,
    desc: "Internt standup",
  },
];

export function computeDeptCapacity() {
  return DEPARTMENTS.map((d) => {
    let assigned = 0;
    let tracked = 0;
    CLIENTS.filter((c) => c.status === "active").forEach((c) => {
      const pct = (c.allocation[d.id] || 0) / 100;
      assigned += c.hoursBudget * pct;
      tracked += c.hoursThisMonth * pct;
    });
    return {
      dept: d.id,
      capacity: d.capacity,
      assigned: Math.round(assigned),
      tracked: Math.round(tracked),
    };
  });
}

export const NPS_TEMPLATES = [
  {
    id: "default",
    name: "Standard (DK)",
    subject: "Hvordan oplever du samarbejdet med Searchmind?",
    body: `Hej {{firstName}},

Vi vil rigtig gerne høre hvordan du oplever samarbejdet.
På en skala fra 0–10, hvor sandsynligt er det at du vil anbefale Searchmind til en kollega?

[ Klik her for at svare ]

Det tager under et minut, og din feedback er guld værd.

Mvh
{{accountManager}}
Searchmind`,
  },
  {
    id: "friendly",
    name: "Venlig tone",
    subject: "Et hurtigt spørgsmål fra os 👋",
    body: `Hej {{firstName}}!

Jeg håber du har det godt. Jeg vil blot høre — hvordan synes du det går med os hos Searchmind?

Kan du bruge 30 sekunder på at give os en score fra 0–10?

Tak for altid god energi!
— {{accountManager}}`,
  },
  {
    id: "formal",
    name: "Formel",
    subject: "Evaluering af samarbejde — Searchmind",
    body: `Kære {{firstName}},

Som led i vores løbende kvalitetsarbejde udsender vi kvartalsvis NPS-måling til vores kunder.

På en skala fra 0–10, hvor sandsynligt er det at du vil anbefale Searchmind?

Med venlig hilsen,
{{accountManager}}
Searchmind ApS`,
  },
];

/** Seneste bureau-runde — invitationer/svar til KPI (mock). */
export const NPS_LAST_ROUND = {
  invitations: 262,
  responses: 184,
  medianHoursToRespond: 36,
};

/**
 * 12-punkts bureau-trend (mock) — sidste værdi kan overskrives med live gennemsnit i NPS-siden.
 */
export const NPS_AGENCY_TREND_BASE = [46, 47, 46, 48, 49, 50, 51, 50, 52, 53, 53, 52];

/** Planlagte / kladder til næste NPS-udsving (mock kø). */
export const NPS_UPCOMING_SENDS = [
  {
    id: "ns-1",
    clientId: "c-nordvig",
    wave: "Q2-2026",
    plannedAt: "2026-05-12",
    templateId: "default",
    status: "scheduled",
  },
  {
    id: "ns-2",
    clientId: "c-folio",
    wave: "Q2-2026",
    plannedAt: "2026-05-14",
    templateId: "friendly",
    status: "scheduled",
  },
  {
    id: "ns-3",
    clientId: "c-helio",
    wave: "Recovery-puls",
    plannedAt: "2026-05-09",
    templateId: "formal",
    status: "draft",
  },
  {
    id: "ns-4",
    clientId: "c-torv",
    wave: "Q2-2026",
    plannedAt: "2026-05-18",
    templateId: "default",
    status: "scheduled",
  },
  {
    id: "ns-5",
    clientId: "c-kyst",
    wave: "Q2-2026",
    plannedAt: "2026-05-20",
    templateId: "friendly",
    status: "scheduled",
  },
  {
    id: "ns-6",
    clientId: "c-vaerft",
    wave: "Ad-hoc triage",
    plannedAt: "2026-05-07",
    templateId: "formal",
    status: "review",
  },
];
